Bài 1. Điểm môn học của một nhóm SV được cho như bên dưới:
| Sinh viên | BT cá nhân| Báo cáo |Giữa kỳ |Cuối kỳ	 |
|-------|-------|-------|-------|-------|
| A | 7 | 8 |9 |5 |
| B | 8 | 7 |4|6 |
| C | 7 |5 |8 |6 |
| D| 6 | 8 |5 |4 |
| E | 9 | 9 |8 |7 |
| F | 10 | 8 |9|8 |

| Tỷ lệ % điểm |      |
|:-------|-------:|
| BT cá nhân | 10% |
| Báo cáo | 20% |
| Giữa kỳ | 30% |
| Cuối kỳ| 40% |

Hãy nhập dữ liệu điểm vào ở dạng ma trận, tính ra điểm trung bình của từng HS và cho biết SV nào qua môn (điểm TB >= 5.0).

In [16]:
# Nhập dữ liệu điểm
diem_matrix = [
    [7, 8, 9, 5],
    [8, 7, 4, 6],
    [7, 5, 8, 6],
    [6, 8, 5, 4],
    [9, 9, 8, 7],
    [10, 8, 9, 8]
]

# Tính điểm trung bình của từng sinh viên
diem_tb_sv = [(row[0] * 0.1 + row[1] * 0.2 + row[2] * 0.3 + row[3] * 0.4) for row in diem_matrix]

# Xác định sinh viên nào đã qua môn (điểm trung bình >= 5.0)
sinh_vien_qua_mon = [chr(ord('A') + i) for i, diem_tb in enumerate(diem_tb_sv) if diem_tb >= 5.0]

# In điểm trung bình của từng sinh viên
for i, diem_tb in enumerate(diem_tb_sv):
    print(f"Sinh viên {chr(ord('A') + i)}: Điểm trung bình = {diem_tb:.2f}")

# In sinh viên đã qua môn
print("\nSinh viên đã qua môn:")
print(", ".join(sinh_vien_qua_mon))


Sinh viên A: Điểm trung bình = 7.00
Sinh viên B: Điểm trung bình = 5.80
Sinh viên C: Điểm trung bình = 6.50
Sinh viên D: Điểm trung bình = 5.30
Sinh viên E: Điểm trung bình = 7.90
Sinh viên F: Điểm trung bình = 8.50

Sinh viên đã qua môn:
A, B, C, D, E, F


Bài 2.
Sinh ngẫu nhiên ra 2 ma trận kích thước 3 x 3 và có các phần tử nguyên từ 0 đến 10.
a)	Tính tổng phần tử của mỗi ma trận.
b)	So sánh norm của vector hàng 1 và vector hàng 3 của hai ma trận.
c)	Tìm ma trận C, D, E là tổng, hiệu, tích của hai ma trận trên.
Gợi ý: sử dụng lệnh np.random.randint(?, size=(?, ?)).


In [6]:
import numpy as np

# Sinh ngẫu nhiên hai ma trận kích thước 3x3 với các phần tử nguyên từ 0 đến 10
matrix_A = np.random.randint(0, 11, size=(3, 3))
matrix_B = np.random.randint(0, 11, size=(3, 3))

# a) Tính tổng phần tử của mỗi ma trận
sum_A = np.sum(matrix_A)
sum_B = np.sum(matrix_B)

print("a) Tổng phần tử của ma trận A:", sum_A)
print("   Tổng phần tử của ma trận B:", sum_B)

# b) So sánh norm của vector hàng 1 và vector hàng 3 của hai ma trận
norm_row1_A = np.linalg.norm(matrix_A[0, :])
norm_row3_A = np.linalg.norm(matrix_A[2, :])

norm_row1_B = np.linalg.norm(matrix_B[0, :])
norm_row3_B = np.linalg.norm(matrix_B[2, :])

print("\nb) Norm của vector hàng 1 của ma trận A:", norm_row1_A)
print("   Norm của vector hàng 3 của ma trận A:", norm_row3_A)
print("   Norm của vector hàng 1 của ma trận B:", norm_row1_B)
print("   Norm của vector hàng 3 của ma trận B:", norm_row3_B)

# c) Tìm ma trận C, D, E là tổng, hiệu, tích của hai ma trận trên
matrix_C = matrix_A + matrix_B
matrix_D = matrix_A - matrix_B
matrix_E = np.dot(matrix_A, matrix_B)

print("\nc) Ma trận C (Tổng):")
print(matrix_C)

print("\n   Ma trận D (Hiệu):")
print(matrix_D)

print("\n   Ma trận E (Tích):")
print(matrix_E)


a) Tổng phần tử của ma trận A: 60
   Tổng phần tử của ma trận B: 47

b) Norm của vector hàng 1 của ma trận A: 12.449899597988733
   Norm của vector hàng 3 của ma trận A: 12.68857754044952
   Norm của vector hàng 1 của ma trận B: 8.831760866327848
   Norm của vector hàng 3 của ma trận B: 7.681145747868608

c) Ma trận C (Tổng):
[[12 11 12]
 [10 18 12]
 [ 7 10 15]]

   Ma trận D (Hiệu):
[[-2  7  2]
 [-4  0  0]
 [ 1  8  1]]

   Ma trận E (Tích):
[[119  98 128]
 [102  93 111]
 [115  97 130]]


Bài 3.
Hãy dùng lệnh để sinh ra vector độ dài 21 với các phần tử từ a đến b nào đó. Chẳng hạn: a = 0, b = 100 hoặc a = 10.5, b = 50.
a)Dùng lệnh split, chia nhỏ vector kia ra thành 3 vector con, đặt là u, v, w.
b)Tính u*v và v.dot(w)
c)Tính shape của u trước và sau khi transpose, nhận xét.
Gợi ý: lệnh np.linspace(a, b, c) với a, b là các số thực và c là số nguyên dương cho biết số phần tử cách đều nhau trong [a;b]


In [14]:
import numpy as np

# Sinh vector độ dài 21 với các phần tử từ a đến b
a = 0
b = 100
vector_x = np.linspace(a, b, 21)

# a) Chia nhỏ vector thành 3 vector con u, v, w
u, v, w = np.split(vector_x, [7, 14])
print("Vecto u: ",u)
print("vecto v: ",v)
print("Vecto w: ",w)
# b) Tính u*v và v.dot(w)
uv_product = u * v
vw_dot_product = np.dot(v, w)

print("b) Tích vô hướng của u và v:")
print(uv_product)
print("\n   Tích vô hướng của v và w:")
print(vw_dot_product)

# c) Tính shape của u trước và sau khi transpose, nhận xét
shape_u_before_transpose = u.shape
u_transposed = u.reshape((u.shape[0], 1))  
shape_u_after_transpose = u_transposed.shape

print("\nc) Shape của u trước khi transpose:", shape_u_before_transpose)
print("   Shape của u sau khi transpose:", shape_u_after_transpose)


Vecto u:  [ 0.  5. 10. 15. 20. 25. 30.]
vecto v:  [35. 40. 45. 50. 55. 60. 65.]
Vecto w:  [ 70.  75.  80.  85.  90.  95. 100.]
b) Tích vô hướng của u và v:
[   0.  200.  450.  750. 1100. 1500. 1950.]

   Tích vô hướng của v và w:
30450.0

c) Shape của u trước khi transpose: (7,)
   Shape của u sau khi transpose: (7, 1)


Nhận xét: Việc transpose vector cột (1D array) thành vector cột (2D array) sẽ tạo ra một ma trận có shape (n, 1), trong đó n là số phần tử của vector gốc. Trong trường hợp tren, sau khi transpose, shape của vector u đã thay đổi từ (7,) thành (7, 1).